apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: mydvwa
  labels:
    app: mydvwa
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: mydvwa
    targetPort: 80
  selector:
    app: mydvwa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydvwa
  name: mydvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydvwa
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mydvwa
    spec:
      containers:
      - name: mydvwa
        image: CONTAINER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 80
