apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: mydvwa
  labels:
    app: mydvwa
spec:
  type: NodePort
  ports:
  - port: 80
    name: mydvwa
    targetPort: 80
    nodePort: 30200
  selector:
    app: mydvwa
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mydvwa
  name: mydvwa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mydvwa
    spec:
      containers:
      - name: mydvwa
        image: $K8S_REGISTRY/mydvwa:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: cluster-registry
