---
version: 0.2
phases:
  install:
    commands:
      - apt-get update #&& apt-get -y install python3-pip && pip3 install --upgrade awscli
      - openssl s_client -connect $SMARTCHECK_HOST:443 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > smcert.crt
      - cp smcert.crt /usr/local/share/ca-certificates/$PRE_SCAN_REPOSITORY.crt
      - update-ca-certificates
  pre_build:
    commands:
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  build:
    commands:
      - docker build --tag $PRE_SCAN_REPOSITORY/$TAG .
  post_build:
    commands:
      - >-
        docker run -v /var/run/docker.sock:/var/run/docker.sock
        deepsecurity/smartcheck-scan-action
        --image-name "$PRE_SCAN_REPOSITORY/$TAG"
        --findings-threshold "{\"malware\":0,\"vulnerabilities\":{\"defcon1\":0,\"critical\":0,\"high\":0},\"contents\":{\"defcon1\":0,\"critical\":0,\"high\":1},\"checklists\":{\"defcon1\":0,\"critical\":0,\"high\":0}}"
        --preregistry-host="$PRE_SCAN_REPOSITORY"
        --smartcheck-host="$SMARTCHECK_HOST"
        --smartcheck-user="$SMARTCHECK_USER"
        --smartcheck-password="$SMARTCHECK_PWD"
        --insecure-skip-tls-verify
        --preregistry-scan
        --preregistry-user "$PRE_SCAN_USER"
        --preregistry-password "$PRE_SCAN_PWD" 
#artifacts:
#  files: build.json
