---
version: 0.2
phases:
  install:
    commands:
      - apt-get update && apt-get -y install python3-pip && pip3 install --upgrade awscli
      - openssl s_client -connect $SMARTCHECK_HOST:443 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > smcert.crt
      - cp smcert.crt /usr/local/share/ca-certificates/$PRE_SCAN_REPOSITORY.crt
      - update-ca-certificates
  pre_build:
    commands:
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - docker login -u $PRE_SCAN_USER -p $PRE_SCAN_PWD $PRE_SCAN_REPOSITORY
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker pull $PRE_SCAN_REPOSITORY/$TAG
      - docker tag $PRE_SCAN_REPOSITORY/$TAG $REPOSITORY_URL:$TAG
      - docker push $REPOSITORY_URL:$TAG